### ISSUE TITLE
Drop base64 encoding requirement from ResourceDescriptor.contents?

### ISSUE THREAD

**Issue by wlynch** [in-toto/attestation#188]
(originally from https://github.com/slsa-framework/slsa/issues/834)

Minor piece of feedback / question:

ResourceDescriptor.contents is currently described as:

> base64-encoded bytes, optional

I think it's reasonable to enforce character class constraints on this field, but do we need to go as far as to say this should always be base64 encoded? I'm thinking about simple key/value pairs contained in SLSA `byproducts` that would use ASCII encoding - requiring base64 around these may be unnecessary. 🤔

The description also says:

> The semantics are up to the producer and consumer. The uri or mediaType MAY be used by the producer as hints for how consumers should parse content.

RFC 6838 already has a section for encoding requirements: https://www.rfc-editor.org/rfc/rfc6838.html#section-4.8. Perhaps this is enough to inform to clients what the encoding expectations are for this field?

Or is the right way to read this "contents need to be base64-compatible" - e.g. if the value itself is a valid base64 string, that's okay? (though this is also tricky because there are different base64 encodings)

**Comment by MarkLodato** [comment]
The type of this field should just be `bytes`, not `base64-encoded bytes`. Base64 is only used to convert fields of type `bytes` into JSON, since JSON does not support `bytes` natively. When the message is encoded using something like protobuf or CBOR that natively supports `bytes`, there is no base64. In other words, the API should just expose bytes and not expose the base64 at all.

Note that the [protobuf schema for ResourceDescriptor](https://github.com/in-toto/attestation/blob/e53cd3b10d4a7a8dcab5c9efd87bedd006eba270/protos/in_toto_attestation/v1/resource_descriptor.proto#L19) uses type `bytes`, which gets automatically encoded as base64 via the [proto-to-JSON mapping](https://protobuf.dev/programming-guides/proto3/#json).

I think we should fix the documentation to make this more clear.

Does that help?

**Comment by wlynch** [comment]
ahhh - makes sense. Thanks!

+1 for updating the docs.

**Comment by marcelamelara** [comment]
Can confirm that the intent is to have the type of the `content` field be bytes, definitely thought we had already fixed this, apologies. Will update the documentation.
