### ISSUE TITLE
Define a "attestation bundle" data structure and naming convention

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#38]
_Copied from https://github.com/secure-systems-lab/signing-spec/issues/20._

We need a **data structure** and **file naming convention** to associate multiple attestations to a single software artifact.

### Motivating use case

Suppose file `foo.out` is associated with two attestations, both of which are required by the layout of `foo.out`:

* Provenance: the build system generates a link saying that `foo.out` was produced from material `foo.c`.
* Vulnerability scan: a scanner generates a link saying that `foo.out` is free of known vulnerabilities.

The build system and the scanner need to know where to place the links on the filesystem, and the verifier needs to know how to find those links when evaluating `foo.out`.

### Data structure

Define a "bundle" data structure containing multiple attestations (i.e. multiple [DSSEs](https://github.com/secure-systems-lab/dsse)).

Ideas:

* [JSON Lines](https://jsonlines.org/)
* ZIP file with particular naming convention
* JSON object or array

### File naming convention

Define a convention for locating the attestation bundle related to a given file on disk.

Proposal: `<file>.<bundle_extension>`

Example: If we choose JSON Lines, perhaps the attestations for `foo.out` could be found in `foo.out.intoto.jsonl`?

**Comment by TomHennen** [comment]
I'd like to propose we go with JSON Lines.

1. I think it's pretty easy.
2. It doesn't require any extra parsing of all the attestations (as a JSON object/array would)
3. It migrates easily to other metadata stores that can store text (where zip files might be tricky).

Ideally I think the extension should reference dsse, so `foo.out.dsse.jsonl`?  Otherwise `foo.out.intoto.jsonl` would be fine.

FWIW getting this defined might help with [how to handle cert chains](https://github.com/secure-systems-lab/dsse/issues/39) and help us clarify that really we expect there to be multiple attestations for different purposes and you can have specialized ones along with 'standardized' ones.

**Comment by MarkLodato** [comment]
I'm OK with this, but it would be good to get input from others.

**Comment by trishankatdatadog** [comment]
Are there good reasons for JSON Lines, and not just good old-fashioned JSON?

**Comment by TomHennen** [comment]
[This site](https://hackernoon.com/json-lines-format-76353b4e588d) gives some good reasoning.

tl;dr: With regular JSON you'd have to read the entire file to parse _or add_ a single record.

**Comment by trishankatdatadog** [comment]
> [This site](https://hackernoon.com/json-lines-format-76353b4e588d) gives some good reasoning.
> 
> tl;dr: With regular JSON you'd have to read the entire file to parse _or add_ a single record.

I guess my only concern right now is that it can become a bit unwieldy with very large payloads.

**Comment by TomHennen** [comment]
Updated the PR summary to include a description of why we're choosing JSON Lines.

Also added a [Viewing Bundles](https://github.com/in-toto/attestation/blob/781fdd1f74214577342d354502d43f8699812200/spec/bundles.md#viewing-bundles) section to bundles.md to show a good way for dealing with large attestations (I think this is what you were suggesting might be hard?).
