### ISSUE TITLE
Question: Why is the protocol included on _type and predicateType?

### ISSUE THREAD

**Issue by dlorenc** [in-toto/attestation#41]
They read: `https://in-toto.io/Provenance/v0.1` and `https://in-toto.io/Statement/v0.1`.

If these are just unique identifiers, I'd imagine we drop the `https:` portion. We don't ever intend for there to be real content served from them, do we?

**Comment by MarkLodato** [comment]
Simply because we chose to use "URI" instead of inventing some new concept. I'd be fine dropping the protocol - it just requires a little more documentation. I'd also be OK making it case-insensitive or lowercase as discussed on another thread.

The spec says that the link SHOULD resolve a human-readable description. The intention is to set up redirects:
- Provenance/v0.1 => https://github.com/in-toto/attestation/blob/main/spec/predicates/provenance.md (versioned)
- Statemetn/v0.1 => https://github.com/in-toto/attestation/blob/main/spec/README.md (versioned)

**Comment by dlorenc** [comment]
Would a standard IANA MediaType make sense instead of a URI?

**Comment by MarkLodato** [comment]
We considered MediaType but thought that URI was a better-known collision-resistant string.
1.  Domain names are unambiguous. As an example from @TomHennen, Universities of Washington and Wisconson both call themselves "UW" but only the former is `uw.edu` (the latter is `wisc.edu`). They could both potentially use the `application/vnd.uw.` prefix.
2. People are likely less familiar with the `application/vnd.<name>.` namespace.
3. URLs are self-documenting if you set up a redirect to your docs.

FWIW, Kubernetes uses the "URL minus the https://" convention.

But I'm not too strongly tied to the idea.

**Comment by letmaik** [comment]
Media types are typically used for file formats, while URIs are used for schemas. In this case they are JSON-compatible schemas. If you use media types, then you would have to restrict it to JSON media types to still make sense (since the predicate is put into the statement object), and even then, the general assumption is that the "media" is preserved as-is and not JSON-parsed and inserted into an existing object. Using URIs makes sense to me. It also allows to re-use schemas with different payload media types (e.g. `application/vnd.in-toto+cbor`) since the schema is not strictly tied to a specific file format. 

Another argument is that formats like CycloneDX already have built-in integrity support. If the media type of such formats would be used directly, then it would pull in the whole format, not just the claims schema, and this is not the intention here.

**Comment by dlorenc** [comment]
> FWIW, Kubernetes uses the "URL minus the https://" convention.

Yeah they also limit the path to one "/" annoyingly IIRC

**Comment by MarkLodato** [comment]
Thanks @letmaik! Yes, that too!

@letmaik what do you think about dropping the `https://`?

**Comment by letmaik** [comment]
I would keep `https://`, taking inspiration from the Linked Data universe where everything is a URI. I also agree with the self-documenting nature of it.

**Comment by dlorenc** [comment]
If we're actually expecting content to be served from the URI (docs, etc.) this makes more sense. Thanks!

I'm not quite sure I agree on the classification between mediaType and URI though. For example, OCI uses `mediaTypes` to represent structured data with an encoding, like this:

`mediaType": "application/vnd.oci.image.manifest.v1+json"`

**Comment by MarkLodato** [comment]
Sounds like there is agreement that URl makes sense. I'll close this issue but please reopen if I misjudged.
