### ISSUE TITLE
Provenance: add ability to add extensions?

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/attestation#8]
We almost definitely will not get the Provenance schema right on the first try. When there is some new information that producers want to add to the provenance, it would be nice if they had a way to do so without having to either fork the spec or wait for a new version that adds that feature.

A few ideas:

- Not allowed.
- Allow additional fields to be added to any object, with any name.
  - Example: `{"materials": [{..., "someNewField": "yay!"}]}`
  - Pro: Simple.
  - Con: Possibility of name clash, where two producers use the same name but with different meaning.
  - Con: Precludes the "minor version" idea from #4, since a field of that name may be added in a future version.
- Allow additional fields to be added to any object, with constraints:
  - Field name MUST be a URI (to address the two cons from above).
  - The meaning of all other fields MUST be unchanged if that field is ignored. For example, if you add a `{"recipe": {..., "https://example.com/foo": true}}`, then it should be perfectly safe for a consumer to ignore that new field.
- Add an `extensions` field to each object, with basically the same constraints as above.

I'm leaning towards the second approach (URI fields) but would be happy to hear opinions.

**Comment by TomHennen** [comment]
URI fields sounds good to me.

"then it should be perfectly safe for a consumer to ignore that new field."

This statement might need some tightening up.  E.g. people might have added the field so that they or someone else can write some policy around it.  It would be a violation of the policy to ignore that field.

Maybe

"then policy evaluation that does not use the new field should be unaffected" ?

**Comment by MarkLodato** [comment]
Agreed. We'll have to work out wording in the PR.

**Comment by aysylu** [comment]
The preferred option with URIs for additional field names makes sense to me.
